import { PDFDocument } from 'pdf-lib'
import { parseVerificationSignature, generateCertificateContentHash, generateVerificationSignature } from './pdf-generator'
import { Certificate } from './types'
import { certificateStore } from './store'

export interface PDFVerificationResult {
  isValid: boolean
  isTampered: boolean
  certificate?: {
    id: string
    patient: string
    type: string
    issuer: string
    date: string
    hash: string
  }
  originalCertificate?: Certificate
  message: string
  details: string[]
}

export async function extractPDFMetadata(pdfBuffer: ArrayBuffer): Promise<{
  keywords?: string
  title?: string
  author?: string
  subject?: string
  creator?: string
  text?: string
}> {
  try {
    const pdfDoc = await PDFDocument.load(pdfBuffer)
    
    return {
      title: pdfDoc.getTitle() || undefined,
      author: pdfDoc.getAuthor() || undefined,
      subject: pdfDoc.getSubject() || undefined,
      keywords: pdfDoc.getKeywords() || undefined,
      creator: pdfDoc.getCreator() || undefined,
    }
  } catch (error) {
    console.error('Failed to extract PDF metadata:', error)
    return {}
  }
}

export async function verifyUploadedPDF(pdfBuffer: ArrayBuffer): Promise<PDFVerificationResult> {
  const details: string[] = []
  
  try {
    // Step 1: Extract metadata from PDF
    const metadata = await extractPDFMetadata(pdfBuffer)
    details.push('PDF loaded successfully')
    
    // Step 2: Check if it's a HealthCert document
    if (metadata.creator !== 'HealthCert Blockchain System') {
      return {
        isValid: false,
        isTampered: false,
        message: 'This PDF was not generated by HealthCert system',
        details: [...details, 'Creator signature not found - not a HealthCert document'],
      }
    }
    details.push('HealthCert signature found')
    
    // Step 3: Extract verification data from keywords
    const keywords = metadata.keywords || ''
    const parts = keywords.split(',')
    
    if (parts.length < 2) {
      return {
        isValid: false,
        isTampered: true,
        message: 'Certificate verification data is missing or corrupted',
        details: [...details, 'Verification metadata is incomplete - possible tampering'],
      }
    }
    
    const contentHash = parts[0]
    const verificationSig = parts[1]
    
    details.push(`Content hash found: ${contentHash.substring(0, 20)}...`)
    
    // Step 4: Parse the verification signature
    const parsedData = parseVerificationSignature(verificationSig)
    
    if (!parsedData) {
      return {
        isValid: false,
        isTampered: true,
        message: 'Certificate signature is invalid or corrupted',
        details: [...details, 'Failed to parse verification signature - document may be tampered'],
      }
    }
    
    details.push(`Certificate ID extracted: ${parsedData.id}`)
    details.push(`Patient name: ${parsedData.patient}`)
    
    // Step 5: Look up the original certificate in our database
    const originalCert = certificateStore.getById(parsedData.id)
    
    if (!originalCert) {
      return {
        isValid: false,
        isTampered: false,
        certificate: parsedData,
        message: 'Certificate not found in system database',
        details: [...details, 'Certificate ID not found - may be from a different system'],
      }
    }
    
    details.push('Original certificate found in database')
    
    // Step 6: Verify the hash matches
    const expectedHash = generateCertificateContentHash(originalCert)
    const expectedSig = generateVerificationSignature(originalCert)
    
    // Check if content hash matches
    if (contentHash !== expectedHash) {
      return {
        isValid: false,
        isTampered: true,
        certificate: parsedData,
        originalCertificate: originalCert,
        message: 'TAMPERED: Certificate content has been modified',
        details: [
          ...details, 
          'Content hash mismatch detected',
          `Expected: ${expectedHash}`,
          `Found: ${contentHash}`,
          'The PDF content has been altered after generation',
        ],
      }
    }
    
    details.push('Content hash verified')
    
    // Step 7: Verify signature data matches
    const parsedOriginal = parseVerificationSignature(expectedSig)
    
    if (!parsedOriginal || 
        parsedData.patient !== parsedOriginal.patient ||
        parsedData.type !== parsedOriginal.type ||
        parsedData.issuer !== parsedOriginal.issuer) {
      return {
        isValid: false,
        isTampered: true,
        certificate: parsedData,
        originalCertificate: originalCert,
        message: 'TAMPERED: Certificate data has been modified',
        details: [
          ...details,
          'Signature data mismatch',
          'Certificate details do not match original records',
        ],
      }
    }
    
    details.push('Signature verified')
    details.push('All verification checks passed')
    
    // Step 8: Certificate is valid
    return {
      isValid: true,
      isTampered: false,
      certificate: parsedData,
      originalCertificate: originalCert,
      message: 'AUTHENTIC: Certificate is valid and has not been tampered with',
      details,
    }
    
  } catch (error) {
    return {
      isValid: false,
      isTampered: false,
      message: 'Failed to verify PDF',
      details: [...details, `Error: ${error instanceof Error ? error.message : 'Unknown error'}`],
    }
  }
}

// Quick check function for client-side
export function extractCertificateIdFromPDF(keywords: string): string | null {
  try {
    const parts = keywords.split(',')
    if (parts.length < 2) return null
    
    const verificationSig = parts[1]
    const parsed = parseVerificationSignature(verificationSig)
    
    return parsed?.id || null
  } catch {
    return null
  }
}
