import { NextRequest, NextResponse } from 'next/server'
import { certificateDb, userDb } from '@/lib/db'
import { blockchainService } from '@/lib/blockchain'
import { decodeSession } from '@/lib/session'
import { Certificate } from '@/lib/types'
import { randomUUID } from 'crypto'

export async function GET(request: NextRequest) {
  const sessionCookie = request.cookies.get('session')
  
  if (!sessionCookie) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const session = decodeSession(sessionCookie.value)
  
  if (!session) {
    return NextResponse.json({ error: 'Invalid session' }, { status: 401 })
  }

  let certificates: Certificate[]

  if (session.role === 'admin') {
    certificates = await certificateDb.getAll()
  } else {
    certificates = await certificateDb.getByPatientId(session.userId)
  }

  return NextResponse.json({ certificates })
}

export async function POST(request: NextRequest) {
  const sessionCookie = request.cookies.get('session')
  
  if (!sessionCookie) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const session = decodeSession(sessionCookie.value)
  if (!session || session.role !== 'admin') {
    return NextResponse.json({ error: 'Admin access required' }, { status: 403 })
  }

  try {
    const body = await request.json()
    const { patientId, certificateType, issuedBy, issueDate, expiryDate, description } = body

    if (!patientId || !certificateType || !issuedBy || !issueDate || !description) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Get patient details
    const patient = await userDb.getById(patientId)
    if (!patient) {
      return NextResponse.json({ error: 'Patient not found' }, { status: 404 })
    }

    // Generate a temporary ID for blockchain storage (actual ID is generated by DB)
    const tempCertId = randomUUID()

    // Store on blockchain
    const blockchainResult = await blockchainService.storeCertificate({
      certificateId: tempCertId,
      patientId,
      certificateType,
      issuedBy,
      issueDate: new Date(issueDate),
    })

    // Create certificate (UUID is auto-generated by the database)
    const certificate = await certificateDb.create({
      patientId,
      patientName: patient.name,
      patientEmail: patient.email,
      certificateType,
      issuedBy,
      issueDate: new Date(issueDate),
      expiryDate: expiryDate ? new Date(expiryDate) : undefined,
      description,
      blockchainHash: blockchainResult.hash,
      transactionId: blockchainResult.transactionId,
      status: 'verified',
    })

    if (!certificate) {
      return NextResponse.json(
        { error: 'Failed to create certificate' },
        { status: 500 }
      )
    }

    return NextResponse.json({
      message: 'Certificate created and stored on blockchain',
      certificate,
      blockchain: blockchainResult,
    })
  } catch (error) {
    console.error('Certificate creation error:', error)
    return NextResponse.json(
      { error: 'Failed to create certificate' },
      { status: 500 }
    )
  }
}
